name: Production Deploy
on:
  push:
    branches: [stage, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Deploy to production server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --ignore-errors
          path: /
          remote_port: 22
          remote_path: /var/www/professional-shop.stage.bitter.de/
          remote_host: stage.bitter.de
          remote_user: root
          remote_key: ${{ secrets.SSH_KEY }}
