name: Production Deploy
on:
  push:
    branches: [stage, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: export COMPOSER_MEMORY_LIMIT=-1

      - name: Composer
        uses: ramsey/composer-install@v2
        with:
          ignore-cache: "yes"
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.COMPOSER_AUTH }}"}}'

      - name: Deploy to production server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --ignore-errors
          path: /
          remote_port: 65002
          remote_path: /home/u187151543/domains/demo.bitter.de
          remote_host: 213.130.145.194
          remote_user: u187151543
          remote_key: ${{ secrets.SSH_KEY }}
